apiVersion: v1
kind: Service
metadata:
  name: { { include "asgard-app.fullname" . } }
spec:
  type: { { .Values.service.type } }
  selector:
    app: { { include "asgard-app.name" . } }
  ports:
    - protocol: TCP
      port: { { .Values.service.port } }
      targetPort: { { .Values.containerPort } }
