apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: asgard-app-kaniko
  namespace: asgard
rules:
- apiGroups: [""]
  resources: ["pods", "configmaps", "secrets"]
  verbs: ["create", "get", "list", "watch", "delete"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["create", "get", "list", "patch", "update"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["create", "get", "list", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: asgard-app-kaniko
  namespace: asgard
subjects:
- kind: ServiceAccount
  name: asgard-app
  namespace: asgard
roleRef:
  kind: Role
  name: asgard-app-kaniko
  apiGroup: rbac.authorization.k8s.io